@startuml
title Use-Cases für Bildverwaltungssystem
left to right direction

actor "Fotograf" as fotograf
actor "Anderer Benutzer" as benutzer
actor "System" as system

rectangle "Bildverwaltungssystem" {
    (Anmelden im System) as (anmelden)
    (Metadaten \nautomatisch ermitteln) as (meta_auto)
    (Bilder hochladen) as (upload)

    fotograf -- (Ordner verwalten)
    (Ordner verwalten) ..> (anmelden) : includes

    fotograf -- (Bilddateien\nhierarchisch ordnen)
    (Bilddateien\nhierarchisch ordnen) ..> (anmelden) : includes

    fotograf -- (Metadaten bearbeiten)
    (Metadaten bearbeiten) ..> (anmelden) : includes

    fotograf -- (Tags verwalten)
    (Tags verwalten) ..> (anmelden) : includes

    fotograf -- (upload)
    (upload) ..> (anmelden) : includes

    (meta_auto) -- system
    (upload) ..> (meta_auto) : extends

    fotograf -- (Bilder bearbeiten\nmit Filtern)
    (Bilder bearbeiten\nmit Filtern) ..> (anmelden) : includes

    fotograf -- (Bilder exportieren)
    (Bilder exportieren) ..> (anmelden) : includes

    fotograf -- (Ordner freigeben)
    (Ordner freigeben) ..> (anmelden) : includes

    benutzer -- (Freigegebene\nBilder sichten)
    (Freigegebene\nBilder sichten) ..> (anmelden) : includes

}
@enduml
