@startuml
skinparam ParticipantPadding 50

title Ablauf HTTP-Requests

participant "Client [TCP:????]" as Client
participant "Server [TCP:443]" as Server

Client -> Server: Request **1**
note left
    Der **Client** initiiert die TCP-Verbindung
end note
Server -->Client: Response **1**
note right
    Der **Server** kann nur
    darauf antworten.
end note
note left
    Die TCP-Verbindung wird
    nach der Response geschlossen.
end note

...

Client -> Server: Request **2**
Server -->Client: Response **2**

@enduml
