@startuml
title Analyse-Klassendiagramm mit Assoziationen
skinparam shadowing false
hide empty members
' skinparam nodesep 100
' skinparam ranksep 80

class Rolle {}
class Terminal {}
class MagazinBestellListe {}
class Magazin{}
class Gebühr {
    jahr: Number
    betragErwachsen: Number
    betragJugendlich: Number
}

class Lizenz {
    anzExemplare: Number
    beschreibung: Text
}

class Sprache {
    code: Text
    sprache: Text
}

class Rechnung {
    nr: Number
    datum: Date
    typ
    betrag: Number
    bezahltAm: Date
}

class Benutzer {
    login: Text
    passwort: Text
    kartennummer: Text
    aktiv: Boolean
    email: Text
}

class Person {
    name: Text
    vorname: Text
    geburtsdatum: Date
    adresse: Text
    plz: Text
    ort: Text
}

class Autor {
    biografie: Text
}

class Ausleihe {
    ausgeliehenAm: Date
    zurueckAm: Date
}

class Medium {
    titel
    mediennummer
    kurzbeschreibung
    erworbenAm: Date
    zusatzMedium: Medium
    kategorien: Kategorie[]
    stichworte: StichwortTag[]
    altersstufe: Altersstufe
    {static} ausleihdauerTage: Number
    {static} ausleihdauerGebuehr: Number
}

class DigitalesMedium {
    lizenz: Lizenz
}

class EHoerbuch {
    isbn
    autor
    sprache
}

class Ebook {
    isbn
    autor
    sprache
}

class PhysischesMedium {
    standort
    rfidCode
}

class DVD {
    ean
    interpret
}

class CD {
    ean
    interpret
}

class Buch {
    isbn
    autor
    sprache
}

class Hoerbuch {
    isbn
    autor
    sprache
}

class MediumExemplar {
    nummer
    ausleihbar: Boolean
}

class Interpret {

}

class Standort {
    bezeichnung
}

class Kategorie {
    name
}

class StichwortTag {
    bezeichnung
}

class Altersstufe {
    bezeichnung
}

class Reservation {
    reserviertAm
}

class Jahresbeitrag {
    periodeVon: Date
    periodeBis: Date
}


Person <|-- Autor

Medium <|-- DigitalesMedium
Medium <|-- PhysischesMedium

DigitalesMedium <|-- EHoerbuch
DigitalesMedium <|-- Ebook

PhysischesMedium <|-- DVD
PhysischesMedium <|-- CD
PhysischesMedium <|-- Buch
PhysischesMedium <|-- Hoerbuch


' Beziehungen
Gebühr "*" - "*" Benutzer
(Gebühr, Benutzer) .. Jahresbeitrag

Rechnung "1" - "*" Jahresbeitrag
Rechnung "0..*" - "1" Benutzer
Benutzer "0..1" --* "1" Person
Benutzer "*" -- "*" Medium

(Benutzer,Medium) . Reservation: Reservation
note left: Eine Reservation pro Benutzer und Medium
Benutzer "*" -- "*" MediumExemplar
(Benutzer,MediumExemplar) . Ausleihe: Ausleihe
Medium "1" - "*" Medium: Zusatzmedium
Medium "*" - "*" Kategorie
Medium "*" - "1" Interpret
Medium "*" - "*" StichwortTag
Medium "*" - "1" Altersstufe
Lizenz "0..1" -- "*" DigitalesMedium
Standort "1" -- "*" PhysischesMedium
Sprache "1" -up- "*" EHoerbuch
Sprache "1" -up- "*" Ebook
Sprache "1" -up- "*" Buch
Sprache "1" -up- "*" Hoerbuch

@enduml
