@startuml
title Beispiel Software-Architektur mit Paket-Diagramm
skinparam shadowing false
package "UI Layer" {
    rectangle "Terminals" {
        [Terminal-UI] as terminal_ui
    }
    rectangle InternetSeite {
        [VueJS-Frontend] as inet_front
    }
    rectangle "Swing-App" {
        [Management-UI] as management_ui
    }
}

package "Application Logic" {
    [Authentifikation] as auth
    [REST-API] as api
    [Medien-\nManager] as medienmanager
    [Terminal-\nSteuerung] as terminalmanager
    http ->api
    api -down-> auth
    api -down-> medienmanager
}

package "Persistence Layer" {
    [Serialisierung]
    [ORM]
    [DB-Connection] as dbconn
    [ORM] -> [Serialisierung]
    [Serialisierung] -> dbconn
}

terminal_ui --> terminalmanager
inet_front --> http
management_ui --> http
medienmanager --> ORM
auth --> ORM
terminalmanager -> medienmanager
terminalmanager -> auth
@enduml
