@startuml
' Ausrichtung Aktoren - Use-Case:
left to right direction

' aktoren definieren:
actor :Internet-Benutzer: as iusr
actor :Bibliotheks-Benutzer: as bibusr
actor :Mitarbeiter: as bibma
actor :System: as system

' Systemgrenze mit Use-Cases:
rectangle Bibliothekssystem as sys {
    together {
        usecase "Medien am\nTerminal ausleihen" as med_terminal
        usecase "Medien am\nSchalter ausleihen" as med_schalter
    }
    usecase "Medien ausleihen" as med_lease

    usecase "Benutzer\nerfassen" as benutzer_erfassen
    usecase "Medien\nzurückbringen" as med_back
    usecase "Medien\nerfassen" as med_create
    usecase "Medien\nentfernen" as med_delete
    usecase "Verfügbarkeit\nversenden" as send_availability
    usecase "Mahnung\nversenden" as send_reminder
    usecase "Magazin-Medium\nbestellen" as magazin_order
    usecase "Magazin-Liste erzeugen" as magazin_list

    usecase "Ausleihen via\nWeb abrufen" as lease_show_web
    usecase "Ausleihen via\nWeb verlängern" as lease_increase_web
    usecase "Ausleihen via\nWeb reservieren" as lease_reserve_web
    usecase "Profil via Web\nanpassen" as profile
    usecase "Benuztzer\nregistrieren" as register
    usecase "Benuztzer\nautorisieren" as login


}
' Beziehungen Aktoren:
bibusr -- med_terminal
iusr -- lease_show_web
iusr -- lease_increase_web
iusr -- lease_reserve_web
iusr -- profile
iusr -- register

bibma -- med_schalter: für Benutzer
bibma -- med_back: für Benutzer
bibma -- benutzer_erfassen: für Benutzer
bibma -- med_create
bibma -- med_delete
bibma -- magazin_list
bibma -- magazin_order: für Benutzer

system -- send_availability
system -- send_reminder

' Beziehungen UCs
med_terminal --|> med_lease
med_schalter --|> med_lease

med_terminal ..> login: <<include>>
lease_show_web ..> login: <<include>>
lease_increase_web ..> login: <<include>>
lease_reserve_web ..> login: <<include>>
profile ..> login: <<include>>
register ..> login: <<include>>

@enduml
