@startuml
' Ausrichtung Aktoren - Use-Case:
left to right direction

' aktoren definieren:
actor :Internet-Benutzer: as iusr
note top of iusr
Aktor:
Am System beteiligt
end note
actor :Bibliotheks-Benutzer: as bibusr
actor :Bibliotheks-\nAngestellte/r: as bibadmin

' Systemgrenze mit Use-Cases:
rectangle Bibliothekssystem as sys {
    usecase "Buch verlängern" as uc1
    usecase "Buch ausleihen" as uc2
    usecase "neues Medium\nerfassen" as uc4
    usecase "Benutzer\nlegitimieren" as uc3
}
note top of sys
    Systemgrenze
end note
note right of uc2
    Use-Case
end note

' Beziehungen:
iusr -- uc1
bibusr -- uc2
note on link
    Interagiert
    mit Use-Case
end note
uc4 -- bibadmin

uc1 .> uc3: <<include>>
uc2 .> uc3: <<include>>

@enduml
