@startuml
title Aktivität: Medien am Terminal ausleihen

|#f8f8f8|Frontend|
start
:Scan Benutzerausweis >

|#f0f0f0|Business Logic|
:Event Scan Ausweis <

|#f8f8f8|Persistenz|
-> Abfrage via User-ID;
:Benutzer laden;

|Business Logic|
if (Benutzer gefunden?) then (Ja)
    :Benutzerdaten prüfen;
    if (Karte prüfen) then (Karte abgelaufen)
        |Frontend|
        :Fehlerausgabe;
        end
    else (Karte i.O)
        |Frontend|
        repeat
        :Scanner aktivieren;
        :Medium-Scan >
        |Business Logic|
        :Scan-Event:\nMedien-ID <
        |Persistenz|
        :Medium laden;
        |Business Logic|
        if (kostenpflichtig?) then (Ja)
            |Frontend|
            :Fehlerausgabe;
            end
        else (Nein)
            |Persistenz|
            :Ausleihdatum speichern;
            |Frontend|
            :Bestätigung anzeigen;
        endif
        repeat while (weitere Medien scannen?) -> ja
        -> nein;
        :ok;
    endif

    |Business Logic|
    :Bestätigung drucken;
    :Benutzer abmelden;
    |Frontend|
    :Logout-Meldung;
    stop
else (Nein)
    |Frontend|
    :Fehlerausgabe;
    end
endif
@enduml
